### ISSUE TITLE
Next.js: SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by ahmadawais** [GoogleChrome/web-vitals#20]
Following the installation in readme with Next.js v9.3.6 (latest) has led to the following issue. `SyntaxError: Unexpected token 'export'` Looks like a cjs module not working in React. 🤔

<details>
 <summary>ERROR (CLICK TO EXPAND!)</summary>

SyntaxError: Unexpected token 'export'
(anonymous function)
/Users/ahmadawais/…/node_modules/web-vitals/dist/web-vitals.min.js:1
Module._compile
internal/modules/cjs/loader.js:892:18
Module._extensions..js
internal/modules/cjs/loader.js:973:10
Module.load
internal/modules/cjs/loader.js:812:32
Function.Module._load
internal/modules/cjs/loader.js:724:14
Module.require
internal/modules/cjs/loader.js:849:19
require
internal/modules/cjs/helpers.js:74:18
web-vitals
webpack:/external "web-vitals":1
> 1 | module.exports = require("web-vitals");
View compiled
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../pages/index.js
/_next/development/server/static/development/pages/index.js:4450:69
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
3
/_next/development/server/static/development/pages/index.js:4996:18
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
▶ 10 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

</details>

**Comment by philipwalton** [comment]
> Looks like a cjs module not working in React.

Hmmm, there aren't any CJS modules anywhere in the `src` directory. And the file being imported in your stack trace is definitely an ES module (see https://unpkg.com/web-vitals@0.2.0/dist/web-vitals.min.js)

Maybe this is an SSR issue? E.g. trying to require modules in node as part of generating the SSR payload and Next not being compatible with ES modules?

cc: @housseindjirdeh who is more familiar with Next.js than I am.

**Comment by ahmadawais** [comment]
The page I am using this on is static and has no functions except the UI function for React's layout with Next.js

**Comment by philipwalton** [comment]
Can you share how you're using this in your project?

By the way, I cloned a Next.js tutorial and tried to build it and saw the same error you did. After playing around with it for a bit, it's pretty clear that the issue is Next.js is trying to `require()` web-vitals on the server, and it's failing to do that (not sure why).

If, on the other hand, I dynamically import web-vitals, it seems to work fine:

```js
import('web-vitals').then(({getCLS, getFID, getLCP}) => {
  getCLS(console.log);
  getFID(console.log);
  getLCP(console.log);
});
```

**Comment by philipwalton** [comment]
I discussed with some of my colleagues (more familiar with Next.js than I am), and they confirmed that Next.js *does not* transpile anything in `node_modules` when either bundling or server-side rendering, so that's likely the issue here.

I'll update the `main` field in `package.json` to be UMD so React/Next.js users who need SSR can import without error, and I'll keep the `module` field ESM so Rollup et al can benefit from the smaller code size.

In the meantime, though, dynamic import should work for just playing around with the library/API.

**Comment by Zizzamia** [comment]
One thing I think is important to pointed out, it's that a developer should not use Web Performance API during SSR, in particular trying to access `PerformanceObserver`.

I wonder if the `try/catch` in https://github.com/GoogleChrome/web-vitals/blob/master/src/lib/observe.ts#L34, is hiding some error during Server Side Rendering. If so, maybe we should check if `PerformanceObserver` is available in the global scope.

@philipwalton what you think?

**Comment by philipwalton** [comment]
#23 should fix this.

@Zizzamia I'm fairly sure the issue is that `web-vitals` modules, in some cases, do things like check `document.visibilityState` or call `addEventListener()` in the top-level module context, which breaks when `required()`-ed in a node environment.

In my opinion, any web framework that does SSR should be stubbing out these browser globals, but based on my initial research it's clear that most of them do not.

While, in the long term, I'd like to work with these frameworks to be more accepting or browser-only modules in SSR, in the immediate term it's simple enough to convert all of the `web-vitals` modules to pure modules.

**Comment by philipwalton** [comment]
@ahmadawais I just released `v0.2.1`, which should fix this. Please give it a try and let me know if you're still having issues.

**Comment by ahmadawais** [comment]
It sadly still doesn't work. 

![image](https://user-images.githubusercontent.com/960133/81291219-ceece000-9082-11ea-9b58-b9528d567b97.png)

After chatting with the Next.js team I was told that it's actually already included in the Next.js core.

![image](https://user-images.githubusercontent.com/960133/81291301-f80d7080-9082-11ea-8e5b-d169ebe30797.png)

**Comment by philipwalton** [comment]
@ahmadawais if you're using SSR, then you'll need to ensure you're not calling `getCLS()`, `getFID()`, `getLCP()`, etc. in any code path that gets invoked on the server.

My change in `v0.2.0` just made sure no browser-only APIs were invoked when _importing_ `web-vitals`, but browser APIs (e.g. `PerformanceObserver`) are required when running those methods, so the best solution is to just not run them on the server.

You can use `useEffect()` (or something similar) to do that:

```js
const HomePage = () => {
  useEffect(() => {
    getCLS(console.log);
    getFID(console.log);
    getLCP(console.log);
  }, [...]);
  return (
    // ...
  );
};
```

As for the Next.js implementation, unfortunately its implementation of these metrics is a bit older and is missing some of the critical checks needed when determining these metrics (e.g. no reporting LCP if the page was loaded in the background). As far as I know, their plan is to update it to use `web-vitals` under the hood.

**Comment by housseindjirdeh** [comment]
@ahmadawais FYI web-vitals was included into Next.js core and merged upstream: https://github.com/zeit/next.js/pull/12650

With version 9.4, you'll only need to create a `reportWebVitals` function in `_app.js` to track web vital metrics (among other custom performance marks and measures)

**Comment by ahmadawais** [comment]
Thanks for letting me know, @housseindjirdeh — I'm looking forward to trying that out.
